version: '3.8'

services:
  calendar-service:
    container_name: "calendar-image"
    build:
      context: .
      dockerfile: calendar-service/Dockerfile
    ports:
      - "9090:9090"
    networks:
      - my-network
    environment:
      - SERVER_PORT=9090
      - CALENDAR_SERVICE_URL=http://calendar-service:9090

  vacation-service:
    container_name: "vacation-image"
    build:
      context: .
      dockerfile: vacation-service/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - my-network
    environment:
      - SERVER_PORT=8080
    depends_on:
      - calendar-service

networks:
  my-network:
    driver: bridge